name: Validate Content

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "7.0" branch
  push:
  pull_request:
    branches: [ "7.0" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
          python -m pip install pyyaml

      - name: Validate Quiz Content
        run: python .github/workflows/validate_quiz.py data